export const MARATHI_DICT: Record<string, string> = {
  "Platform admin": "प्लॅटफॉर्म ॲडमिन",
  "Farmers / buyers": "शेतकरी / खरेदीदार",
  "Lots on market": "बाजारातील लॉट",
  "Active orders": "सक्रिय ऑर्डर्स",
  "Settled value": "निकाली काढलेले मूल्य",
  "Open grievances": "प्रलंबित तक्रारी",
  "Name": "नाव",
  "Role": "भूमिका",
  "District": "जिल्हा",
  "Status": "स्थिती",
  "Revoke": "रद्द करा",
  "Verify": "सत्यापित करा",
  "Saving…": "जतन करत आहे…",
  "Market data sources": "बाजार डेटा स्रोत",
  "Source": "स्रोत",
  "Mode": "मोड",
  "Records": "नोंदी",
  "Latest": "नवीनतम",
  "Freshness": "ताजेपणा",
  "Import": "आयात करा",
  "Importing…": "आयात करत आहे…",
  "All orders": "सर्व ऑर्डर्स",
  "No orders yet.": "अद्याप कोणतीही ऑर्डर नाही.",
  "Recent platform activity": "अलीकडील प्लॅटफॉर्म क्रियाकलाप",
  "✨ Kisan Sahayak": "✨ किसान सहाय्यक",
  "Buyer": "खरेदीदार",
  "verified": "सत्यापित",
  "Posted demands": "नोंदवलेल्या मागण्या",
  "Open offers": "प्रलंबित ऑफर्स",
  "Paid so far": "आतापर्यंत दिलेले पैसे",
  "Needs your attention": "आपल्या लक्ष वेधण्याची गरज",
  "total": "एकूण",
  "Accept counter": "प्रति-ऑफर स्वीकारा",
  "Accepting…": "स्वीकारत आहे…",
  "Decline": "नकार द्या",
  "Declining…": "नकार देत आहे…",
  "Open →": "उघडा →",
  "Your demand": "तुमची मागणी",
  "No demand posted yet.": "अद्याप कोणतीही मागणी नोंदवली नाही.",
  "grade": "दर्जा",
  "Remove": "काढून टाका",
  "Removing…": "काढून टाकत आहे…",
  "Post demand": "मागणी नोंदवा",
  "Posting…": "नोंदवत आहे…",
  "Commodity": "शेतमाल",
  "Quantity (qt)": "प्रमाण (क्विंटल)",
  "Min grade": "किमान दर्जा",
  "Price (₹/qt)": "किंमत (₹/क्विंटल)",
  "Within (days)": "दिवसांच्या आत",
  "Lots on the market": "बाजारातील लॉट",
  "All": "सर्व",
  "Grade": "दर्जा",
  "Suggest a fair offer": "योग्य ऑफर सुचवा",
  "Your offer:": "तुमची ऑफर:",
  "Withdraw offer": "ऑफर मागे घ्या",
  "Withdrawing…": "मागे घेत आहे…",
  "Send offer": "ऑफर पाठवा",
  "Sending…": "पाठवत आहे…",
  "Your orders": "तुमच्या ऑर्डर्स",
  "Offer history": "ऑफरचा इतिहास",
  "Something went wrong": "काहीतरी चूक झाली",
  "Reference": "संदर्भ",
  "Try again": "पुन्हा प्रयत्न करा",
  "Fayda forecast": "फायदा अंदाज",
  "Crop": "पीक",
  "Area (acres)": "क्षेत्र (एकर)",
  "Your yield (qt/acre)": "तुमचे उत्पन्न (क्विंटल/एकर)",
  "Cost / acre (₹)": "खर्च / एकर (₹)",
  "Harvest in (days)": "काढणीला उरलेले दिवस",
  "Calculate": "गणना करा",
  "Scenario": "परिदृश्य",
  "Price": "किंमत",
  "Revenue": "उत्पन्न",
  "Selling costs": "विक्री खर्च",
  "Cultivation cost": "लागवड खर्च",
  "Profit": "नफा",
  "Per acre": "प्रति एकर",
  "Explain these numbers & what to do": "हे आकडे आणि काय करावे ते स्पष्ट करा",
  "Field Nigrani": "फिल्ड निगराणी",
  "Storage sensor": "गोदाम सेन्सर",
  "Field sensor": "शेत सेन्सर",
  "normal": "सामान्य",
  "last reading": "शेवटची नोंद",
  "Register device": "डिव्हाइस नोंदवा",
  "Registering…": "नोंदवत आहे…",
  "Device name": "डिव्हाइसचे नाव",
  "Installed in": "येथे बसवले आहे",
  "Storage": "गोदाम",
  "Field": "शेत",
  "FPO dashboard": "FPO डॅशबोर्ड",
  "My lots": "माझे लॉट",
  "harvested": "काढणी झालेली",
  "Dissolve pool": "पूल विसर्जित करा",
  "Withdraw remaining quantity": "उर्वरित प्रमाण मागे घ्या",
  "SmartSell recommendation": "SmartSell शिफारस",
  "Explain this in my language": "माझ्या भाषेत हे स्पष्ट करा",
  "Quality evidence": "गुणवत्तेचा पुरावा",
  "Upload photo": "फोटो अपलोड करा",
  "Uploading…": "अपलोड करत आहे…",
  "Quality photo": "गुणवत्तेचा फोटो",
  "Farmer": "शेतकरी",
  "Contributed": "योगदान दिले",
  "Share": "हिस्सा",
  "Received": "मिळाले",
  "Pending": "प्रलंबित",
  "Sell now or store?": "आता विकावे की साठवावे?",
  "Verdict:": "निकाल:",
  "Sell now": "आता विका",
  "Projected price": "अंदाजित किंमत",
  "Storage + handling": "साठवणूक + हाताळणी",
  "Net": "निव्वळ रक्कम",
  "vs. sell now": "वि. आता विक्री",
  "Book storage": "गोदाम बुक करा",
  "Cancel": "रद्द करा",
  "Cancelling…": "रद्द करत आहे…",
  "Booking…": "बुक करत आहे…",
  "Facility": "सुविधा",
  "km": "किमी",
  "/qt/day": "/क्विंटल/दिवस",
  "Days": "दिवस",
  "Option": "पर्याय",
  "Distance": "अंतर",
  "Transport": "वाहतूक",
  "Charges": "शुल्क",
  "Net / qt": "निव्वळ / क्विंटल",
  "Net total": "एकूण निव्वळ रक्कम",
  "Confidence": "खात्री",
  "★ best": "★ सर्वोत्तम",
  "farm gate": "शेत बांधावर",
  "Offers": "ऑफर्स",
  "Accept": "स्वीकारा",
  "Counter": "प्रति-ऑफर",
  "Counter price per quintal": "प्रति क्विंटल प्रति-ऑफर किंमत",
  "Reject": "नाकारा",
  "Rejecting…": "नाकारत आहे…",
  "Orders from this lot": "या लॉटवरील ऑर्डर्स",
  "Activity log": "क्रियाकलाप नोंद",
  "Namaste": "नमस्ते",
  "Offers to answer": "उत्तर देण्याच्या ऑफर्स",
  "Received so far": "आतापर्यंत मिळालेले",
  "✨ Ask Kisan Sahayak": "✨ किसान सहाय्यकाला विचारा",
  "Review →": "तपासणी →",
  "Create a digital lot": "डिजिटल लॉट तयार करा",
  "Your lots": "तुमचे लॉट",
  "self-declared": "स्वत: घोषित",
  "Pooled": "एकत्रित",
  "No pending offers": "कोणत्याही प्रलंबित ऑफर्स नाहीत",
  "Maha-Subsidy recommender": "महा-सबसिडी शिफारसकर्ता",
  "Your profile": "तुमची प्रोफाईल",
  "Save profile": "प्रोफाईल जतन करा",
  "Land (acres)": "जमीन (एकर)",
  "Category": "वर्ग",
  "General": "सामान्य",
  "Explain which to apply for first (in my language)": "प्रथम कशासाठी अर्ज करावा ते स्पष्ट करा",
  "Official source ↗": "अधिकृत स्रोत ↗",
  "Avg realised": "सरासरी मिळालेली रक्कम",
  "AI pooling advisor": "AI पूलिंग सल्लागार",
  "Pool member lots": "सदस्यांचे लॉट एकत्रित करा",
  "Pooling…": "एकत्रित करत आहे…",
  "FPO lots": "FPO लॉट",
  "Members": "सदस्य",
  "Land": "जमीन",
  "Open supply": "उपलब्ध पुरवठा",
  "✨ Ask AI": "✨ AI ला विचारा",
  "DEMO MODE — seeded data only": "डेमो मोड — फक्त नमुना डेटा",
  "Farmers": "शेतकरी",
  "Farmer Producer Organisation": "शेतकरी उत्पादक संस्था (FPO)",
  "Buyers": "खरेदीदार",
  "Choose a demo account": "डेमो खाते निवडा",
  "PricePulse": "मंडी भाव (PricePulse)",
  "Highest modal price": "सर्वाधिक सर्वसाधारण किंमत",
  "Spread": "तफावत",
  "Market": "बाजार",
  "Modal": "सर्वसाधारण",
  "Min–max": "किमान-कमाल",
  "Arrivals": "आवक",
  "7d": "७ दि.",
  "30d": "३० दि.",
  "Trend": "रुझान",
  "7-day projection": "७-दिवसांचा अंदाज",
  "today": "आज",
  "qt": "क्विंटल",
  "Not found": "सापडले नाही",
  "Go to my dashboard": "माझ्या डॅशबोर्डवर जा",
  "Seller": "विक्रेता",
  "FPO": "FPO",
  "farmer": "शेतकरी",
  "Quality": "गुणवत्ता",
  "measured": "मोजलेली",
  "Quantity": "प्रमाण",
  "Total value": "एकूण मूल्य",
  "Delivery": "वितरण",
  "Payment": "पैसे देणे",
  "Disputes": "वाद",
  "Agreed at": "संमतीची वेळ",
  "Back to order": "ऑर्डरवर परत जा",
  "Digital trade agreement": "डिजिटल व्यापार करार",
  "SHA-256 fingerprint": "SHA-256 फिंगरप्रिंट",
  "intact": "सुरक्षित",
  " or ": " किंवा ",
  "Back": "मागे",
  "View digital agreement": "डिजिटल करार पहा",
  "Deal value": "व्यवहाराचे मूल्य",
  "created": "तयार केले",
  "Order progress": "ऑर्डरची प्रगती",
  "Next step": "पुढची पायरी",
  "Waiting for": "याची वाट पाहत आहे",
  "Pickup & transport": "पिकअप आणि वाहतूक",
  "Mock provider": "मॉक प्रदाता",
  "Vehicle": "वाहन",
  "Route": "मार्ग",
  "Amount": "रक्कम",
  "Grievances": "तक्रारी",
  "Raised by": "यांनी नोंदवली",
  "Resolution:": "निराकरण:",
  "Resolve": "सोडवा",
  "Resolving…": "सोडवत आहे…",
  "How was this resolved?": "हे कसे सोडवले गेले?",
  "Resolution note": "निराकरण टीप",
  "Raise grievance": "तक्रारी नोंदवा",
  "Submitting…": "सादर करत आहे…",
  "What happened?": "काय झाले?",
  "At least 10 characters": "किमान १० अक्षरे",
  "Audit trail": "ऑडिट ट्रेल (नोंदी)",
  "Working…": "काम करत आहे…",
  "✨ Thinking…": "✨ विचार करत आहे…",
  "Ask again": "पुन्हा विचारा",
  "AI negotiation advice": "AI वाटाघाटी सल्ला",
  "Suggested counter:": "सुचवलेली प्रति-ऑफर:",
  "AI triage & suggested resolution": "AI विश्लेषण आणि सुचवलेले निराकरण",
  "Summary:": "सारांश:",
  "Likely cause:": "संभाव्य कारण:",
  "Suggested resolution:": "सुचवलेले निराकरण:",
  "Evidence to request:": "मागण्यासाठी पुरावा:",
  "Copy suggested resolution": "सुचवलेले निराकरण कॉपी करा",
  "Couldn't reach the server.": "सर्व्हरशी संपर्क होऊ शकला नाही.",
  "Analysing…": "विश्लेषण करत आहे…",
  "✨ Re-check": "✨ पुन्हा तपासा",
  "✨ AI grade": "✨ AI दर्जा",
  "✨ Kisan Sahayak is thinking…": "✨ किसान सहाय्यक विचार करत आहे…",
  "Message": "संदेश",
  "Send": "पाठवा",
  "Stop reading aloud": "वाचणे थांबवा",
  "Read aloud": "मोठ्याने वाचा",
  "■ Stop": "■ थांबवा",
  "🔊 Listen": "🔊 ऐका",
  "Microphone permission denied.": "मायक्रोफोन परवानगी नाकारली.",
  "Couldn't hear that — try again.": "ऐकू आले नाही — पुन्हा प्रयत्न करा.",
  "Stop listening": "ऐकणे थांबवा",
  "Speak": "बोला",
  "● Listening…": "● ऐकत आहे…",
  "🎤 Speak": "🎤 बोला",
  "Create lot": "लॉट तयार करा",
  "Creating…": "तयार करत आहे…",
  "Describe your lot": "तुमच्या लॉटचे वर्णन करा",
  "Reading…": "वाचत आहे…",
  "Fill form": "फॉर्म भरा",
  "Quantity (quintal)": "प्रमाण (क्विंटल)",
  "Harvest date": "काढणीची तारीख",
  "Self-declared grade": "स्वत: घोषित दर्जा",
  "Schemes": "योजना",
  "Marketplace": "बाजारपेठ",
  "Admin": "ॲडमिन",
  "✨ AI Sahayak": "✨ AI सहाय्यक",
  "Demo mode": "डेमो मोड",
  "Switch user": "वापरकर्ता बदला",
  "Log in": "लॉग इन",
  "Create Account": "खाते तयार करा",
  "Full Name": "पूर्ण नाव",
  "Phone Number (10 digits)": "फोन नंबर (१० अंक)",
  "Select Role": "भूमिका निवडा",
  "Select District": "जिल्हा निवडा",
  "Create Account & Login": "खाते तयार करा आणि लॉग इन करा",
  "Create a new demo account": "नवीन डेमो खाते तयार करा"
};
